print("__________          __________")
print("     |                   |    ")
print("     |                   |    ")
print("     |                   |    ")
print("     |                   |    ")
print("               /\\             ")
print("              /  \\            ")