<div align="center">

**LAPORAN PRAKTIKUM**

**STRUKTUR DATA**

**“Tipe Data dan Variabel Pyhton”**

**Disusun Oleh :**

**Fabian Alhadi Zalinov**

**2611531004**

**Dosen Pengampu:**

**Dr. Ir WAHYUDI, ST., MT.**

**Asisten Praktikum:**

**Muhammad Galid Alvero**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji syukur kehadirat Tuhan Yang Maha Esa atas segala rahmat dan karunia-Nya sehingga laporan praktikum Pemrograman Python dengan judul "Tipe Data dan Variabel Python" ini dapat diselesaikan dengan baik dan tepat waktu.

Laporan ini disusun untuk memenuhi tugas praktikum serta memperdalam pemahaman mengenai konsep dasar pemrograman Python, khususnya tentang  pengenalan sintaks dasar Python, penggunaan tipe data dasar (numerik, string, boolean), deklarasi variabel, konstanta, dan interaksi I/O (Input/Output).

Penyusun menyadari bahwa laporan ini masih memiliki kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi kesempurnaan laporan ini di masa mendatang. Semoga laporan ini dapat memberikan manfaat bagi pembaca.

Padang, 2026

Fabian Alhadi Zalinov

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Setelah mengenal dasar penulisan program dan perangkat pendukungnya pada pekan sebelumnya, tahap berikutnya dalam mempelajari pemrograman adalah memahami bagaimana sebuah program menyimpan dan mengolah data. Setiap data yang diproses komputer memiliki tipe tertentu, dan Python sebagai bahasa dengan dynamic typing menentukan tipe data secara otomatis berdasarkan nilai yang diberikan kepada sebuah variabel. Pemahaman terhadap tipe data menjadi penting karena kesalahan dalam menentukan tipe sering menjadi penyebab program gagal berjalan, misalnya ketika masukan pengguna yang sebenarnya bertipe string langsung dibandingkan dengan bilangan.

Di sisi lain, sebuah program tidak dapat berdiri sendiri tanpa interaksi dengan penggunanya. Proses masukan dan keluaran (input/output) melalui fungsi input() dan print() menjadi jembatan antara pengguna dan program. Karena fungsi input() selalu mengembalikan nilai bertipe string, diperlukan proses konversi tipe data (type casting) agar nilai tersebut dapat diolah secara numerik. Selain itu, terdapat nilai-nilai tertentu yang tidak boleh berubah selama program berjalan, seperti batas nilai kelulusan, sehingga diperlukan penerapan konstanta menggunakan modul typing.Final. Oleh karena itu, praktikum pekan ini membahas tipe data, variabel, konstanta, konversi tipe, serta operasi masukan dan keluaran secara terpadu melalui studi kasus sistem registrasi praktikan.

## 1.2 Tujuan
1. Memahami jenis-jenis tipe data dasar pada Python, meliputi string, integer, float, complex, dan boolean.
2. Memahami aturan penulisan dan penamaan variabel yang benar sesuai kaidah case-sensitive serta menghindari penggunaan reserved keywords.
3. Memahami penerapan konstanta menggunakan modul typing.Final sebagai nilai ketetapan dalam program.
4. Memahami penggunaan fungsi input() dan print() untuk operasi masukan dan keluaran, serta proses konversi tipe data (type casting).
5. Memahami penggunaan fungsi bawaan type() untuk memeriksa tipe data dari setiap nilai yang diproses program.

## 1.3 Manfaat
1. Mahasiswa dapat membuat program Python yang menerima masukan dari pengguna dan mengolahnya sesuai tipe data yang tepat, sehingga program terhindar dari kesalahan operasi antar tipe data yang berbeda.
2. Mahasiswa dapat menerapkan operator perbandingan untuk menghasilkan nilai boolean sebagai dasar pengambilan keputusan, yang menjadi bekal untuk mempelajari struktur percabangan dan perulangan pada materi selanjutnya.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori

1. Variabel dan Aturan Penamaan:
Variabel merupakan nama yang digunakan untuk menyimpan nilai di dalam memori komputer. Python menganut sifat case-sensitive, sehingga Nama_1004 dan nama_1004 dianggap sebagai dua variabel yang berbeda. Nama variabel tidak boleh diawali angka, tidak boleh mengandung spasi, dan tidak boleh menggunakan kata kunci bawaan (reserved keywords) seperti if, for, atau class. Penamaan variabel dianjurkan menggunakan huruf kecil dengan pemisah garis bawah (snake case) agar kode mudah dibaca.
2. Tipe Data Dasar Python:
Python menyediakan beberapa tipe data bawaan. Tipe str digunakan untuk menyimpan teks yang ditulis di antara tanda petik tunggal, ganda, maupun petik tiga ("""...""") untuk teks multiline. Tipe int menyimpan bilangan bulat, float menyimpan bilangan desimal, dan complex menyimpan bilangan kompleks yang terdiri atas bagian riil dan imajiner dengan notasi j (contoh: 100+3j). Perlu dicatat bahwa Python tidak memiliki tipe data char tersendiri seperti pada bahasa C, sehingga karakter tunggal tetap direpresentasikan sebagai str dengan panjang satu.
3. Tipe Data Boolean dan Operator Perbandingan:
Tipe bool hanya memiliki dua nilai, yaitu True dan False. Nilai boolean umumnya dihasilkan dari operasi perbandingan menggunakan operator seperti >, <, >=, <=, ==, dan !=. Sebagai contoh, ekspresi nilai_1004 >= BATAS_LULUS_1004 akan menghasilkan True apabila skor yang dimasukkan lebih besar atau sama dengan batas kelulusan, dan False apabila sebaliknya.
4. Konstanta dengan typing.Final:
Python tidak menyediakan kata kunci khusus untuk konstanta. Sebagai gantinya, modul typing menyediakan anotasi Final yang menandakan bahwa sebuah nama tidak dimaksudkan untuk diubah nilainya setelah diinisialisasi. Konstanta dideklarasikan di awal program dan ditulis menggunakan huruf kapital seluruhnya, misalnya BATAS_LULUS_1004: Final = 75.0. Anotasi ini bersifat penanda bagi type checker dan pembaca kode, bukan penguncian nilai secara paksa oleh interpreter.
5. Input, Output, dan Type Casting:
Fungsi print() digunakan untuk menampilkan keluaran ke layar, sedangkan fungsi input() digunakan untuk menerima masukan dari pengguna melalui konsol. Nilai yang dikembalikan input() selalu bertipe str, sehingga apabila masukan tersebut akan diolah secara aritmetika perlu dilakukan konversi tipe data menggunakan fungsi int() atau float(). Proses perubahan tipe data ini disebut type casting.
6. Fungsi type():
Fungsi bawaan type() digunakan untuk mengetahui tipe data dari sebuah nilai atau variabel. Keluaran fungsi ini berupa <class 'tipe'>, misalnya <class 'int'> untuk bilangan bulat. Fungsi ini bermanfaat untuk memverifikasi bahwa proses konversi tipe data telah berjalan sesuai harapan.

## 2.2 Kode Program

### 2.2.1 Program "Numerik_2611531004"
Jalankan sel kode di bawah ini agar Jupyter otomatis menyimpan kodenya beserta outputnya sebagai satu kesatuan (tidak perlu screenshot terpisah untuk hasil run).

In [24]:
# Buat file dengan nama Numerik_2611531004.py
# Buat variabel ditambah 4 digit terakhir NIM contoh: a_1004
#create a variable with numeric type value.
a_1004=100
print("The type of variable having value", a_1004, " is ", type(a_1004))

#create a variable with float value.
b_1004=10.2345
print("The type of variable having value", b_1004, " is ", type(b_1004))

#create a variable with complex value.
c_1004=100+3j
print("The type of variable having value", c_1004, " is ", type(c_1004))

The type of variable having value 100  is  <class 'int'>
The type of variable having value 10.2345  is  <class 'float'>
The type of variable having value (100+3j)  is  <class 'complex'>


**Penjelasan :**
1. Bagian pertama berfungsi untuk membuat variabel bertipe data numerik Integer. Variabel a_1004 diisi dengan nilai 100, yaitu bilangan bulat tanpa angka di belakang koma. Nilai tersebut kemudian ditampilkan ke layar bersama tipe datanya menggunakan fungsi print() yang dipadukan dengan fungsi bawaan type(), sehingga program menghasilkan keluaran berupa nilai 100 beserta keterangan <class 'int'>.
2. Bagian kedua berfungsi untuk membuat variabel bertipe data Float. Variabel b_1004 diisi dengan nilai 10.2345, yaitu bilangan pecahan yang memiliki angka di belakang tanda titik desimal. Sama seperti sebelumnya, nilai dan tipe datanya ditampilkan menggunakan print() dan type() sehingga menghasilkan keterangan <class 'float'>. Bagian ini menunjukkan bahwa Python secara otomatis mengenali tipe data sebuah variabel berdasarkan bentuk nilai yang diberikan (dynamic typing), tanpa perlu dideklarasikan terlebih dahulu.
3. Bagian ketiga berfungsi untuk membuat variabel bertipe data Complex. Variabel c_1004 diisi dengan nilai 100+3j, yang terdiri atas bagian riil (100) dan bagian imajiner (3j). Huruf j merupakan notasi bilangan imajiner pada Python. Hasil pemeriksaan dengan type() menampilkan keterangan <class 'complex'>.

### 2.2.2 Program "String_2611531004"
Jalankan sel kode di bawah ini agar Jupyter otomatis menyimpan kodenya beserta outputnya sebagai satu kesatuan (tidak perlu screenshot terpisah untuk hasil run).

In [25]:
# Buat file dengan nama String_2611531004.py
#nama variabel ditambah 4 digit nim terakhir contoh: nama_1004
#ganti programnya dan data masing2
nama_1004 = "Fabian"
jenis_kelamin_1004 = 'L'
alamat_1004 = """
    Garegeh
    Kec. Mandiangin Koto Selayan
    Kota Bukittinggi
"""
agama_1004 = 'Islam'
print("Nama saya adalah: ", nama_1004)
print("Jenis kelamin saya adalah: ", jenis_kelamin_1004)
print("Alamat saya adalah: ", alamat_1004)
print("Agama saya adalah: ", agama_1004)

Nama saya adalah:  Fabian
Jenis kelamin saya adalah:  L
Alamat saya adalah:  
    Garegeh
    Kec. Mandiangin Koto Selayan
    Kota Bukittinggi

Agama saya adalah:  Islam


**Penjelasan :**
1. Bagian pertama berfungsi untuk mendeklarasikan variabel bertipe string, yaitu nama_1004 dan agama_1004 yang memakai kutip ganda, serta jenis_kelamin_1004 yang memakai kutip tunggal — keduanya sah di Python dan hasilnya sama.
2. Bagian kedua berfungsi untuk menyimpan alamat ke dalam variabel alamat_1004 menggunakan triple quotes ("""..."""). Tanda kutip tiga dipakai supaya teks bisa ditulis dalam beberapa baris sekaligus, dan baris barunya ikut tersimpan apa adanya.
3. Bagian ketiga berfungsi untuk menampilkan isi seluruh variabel ke layar dengan print(). Koma di dalam print() dipakai untuk menggabungkan teks label dengan nilai variabel, dan secara otomatis menambahkan satu spasi di antara keduanya.

### 2.2.3 Program "Boolean_2611531004"
Jalankan sel kode di bawah ini agar Jupyter otomatis menyimpan kodenya beserta outputnya sebagai satu kesatuan (tidak perlu screenshot terpisah untuk hasil run).

In [26]:
# Buat file dengan nama Boolean_2611531004.py
# Buat variabel ditambah 4 digit nim terakhir contoh: nilai_1004
# Deklarasi variabel dengan tipe data Boolean
is_lulus_1004 = True
is_cumlaude_1004 = True

# Menggunakan Boolean
nilai_1004 = 85
batas_lulus_1004 = 75
# Menentukan nilai Boolean dari kondisi
status_kelulusan = nilai_1004 >= batas_lulus_1004  # Hasilnya akan True

print("=== Check Kelulusan ===")
print("Nilai:", nilai_1004)
print("Apakah Lulus?:", status_kelulusan)
if is_lulus_1004 and is_cumlaude_1004:
    print("Selamat, Anda lulus dengan predikat Cum laude!")

=== Check Kelulusan ===
Nilai: 85
Apakah Lulus?: True
Selamat, Anda lulus dengan predikat Cum laude!


**Penjelasan :**
1. Bagian pertama berfungsi untuk mendeklarasikan variabel bertipe data Boolean secara langsung, yaitu is_lulus_1004 dan is_cumlaude_1004 yang diisi nilai True. Tipe Boolean hanya punya dua kemungkinan nilai: True atau False (huruf T dan F wajib kapital).
2. Bagian kedua berfungsi untuk menyiapkan data numerik pembanding, yaitu nilai_1004 = 85 sebagai nilai yang diperoleh dan batas_lulus_1004 = 75 sebagai nilai minimum kelulusan.
3. Bagian ketiga berfungsi untuk menghasilkan nilai Boolean dari sebuah kondisi. Operator perbandingan >= mengevaluasi apakah 85 lebih besar atau sama dengan 75, lalu hasilnya (True) disimpan ke variabel status_kelulusan. Jadi Boolean tidak selalu ditulis manual, tapi bisa lahir dari hasil perbandingan.
4. Bagian keempat berfungsi untuk menampilkan nilai dan status kelulusan ke layar.
5. Bagian kelima berfungsi untuk melakukan percabangan dengan if dan operator logika and. Blok print di dalamnya hanya dijalankan apabila is_lulus_1004 dan is_cumlaude_1004 sama-sama bernilai True; jika salah satunya False, baris tersebut dilewati.

### 2.2.4 Program "Input_2611531004"
Jalankan sel kode di bawah ini agar Jupyter otomatis menyimpan kodenya beserta outputnya sebagai satu kesatuan (tidak perlu screenshot terpisah untuk hasil run).

In [27]:
# Buat file dengan nama Input_2611531004.py
# Buat program untuk menghitung luas persegi panjang
# Nama variabel ditambah 4 digit nim terakhir contoh: panjang_1004
# Program ini menggunakan fungsi input() untuk meminta pengguna
# memasukkan nilai panjang dan lebar persegi panjang.
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer
panjang_1004 = int(input('Masukkan nilai panjang: '))
lebar_1004 = int(input('Masukkan nilai lebar: '))
luas_1004 = int(panjang_1004) * int(lebar_1004)
print("Luas =", luas_1004)

Luas = 20


**Output :**

<div align="center">
<img src="images/output_tugas1.png" width="400"><br>
<em>Gambar 2.1 : Output Program</em>
</div>

**Penjelasan :**
1. Bagian pertama berfungsi untuk meminta masukan dari pengguna. Fungsi input() menampilkan teks petunjuk lalu menunggu pengguna mengetik, dan nilai yang dikembalikannya selalu bertipe string. Karena itu dibungkus int() agar dikonversi menjadi bilangan bulat dan bisa dihitung secara matematis.
2. Bagian kedua berfungsi untuk menghitung luas dengan rumus panjang × lebar menggunakan operator *, lalu menyimpan hasilnya ke variabel luas_1004.
3. Bagian ketiga berfungsi untuk menampilkan hasil perhitungan ke layar.

### 2.2.5 Program "Konstanta_2611531004"
Jalankan sel kode di bawah ini agar Jupyter otomatis menyimpan kodenya beserta outputnya sebagai satu kesatuan (tidak perlu screenshot terpisah untuk hasil run).

In [28]:
# Buat file dengan nama Konstanta_2611531004.py
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# nama variabel ditambah 4 digit nim terakhir contoh: jari_1004

from typing import Final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_1004 = float(input('Masukkan nilai jari-jari: '))
luas_1004 = PI * jari_1004 * jari_1004
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_1004, luas_1004))

pi: 3.140000
Luas lingkaran dengan jari-jari 10.00 adalah 314.00


**Output :**

<div align="center">
<img src="images/output_tugas2.png" width="400"><br>
<em>Gambar 2.2 : Output Program</em>
</div>

**Penjelasan :**
1. Bagian pertama berfungsi untuk mengimpor Final dari modul typing, yaitu penanda yang dipakai untuk mendeklarasikan konstanta.
2. Bagian kedua berfungsi untuk membuat konstanta PI: Final = 3.14. Penulisan dengan huruf kapital adalah konvensi Python untuk nilai yang tidak boleh diubah, dan Final memberi tanda bahwa nilainya tetap. Baris print setelahnya menampilkan nilai PI dengan format %f.
3. Bagian ketiga berfungsi untuk meminta masukan jari-jari dari pengguna. Di sini digunakan float() (bukan int()) karena jari-jari bisa berupa bilangan desimal, misalnya 7.5.
4. Bagian keempat berfungsi untuk menghitung luas lingkaran dengan rumus π × r × r, memanfaatkan konstanta PI yang sudah didefinisikan.
5. Bagian kelima berfungsi untuk menampilkan hasil dengan format terkontrol. Simbol %.2f membulatkan tampilan angka menjadi dua angka di belakang koma, dan nilai penggantinya diambil berurutan dari tuple (jari_1004, luas_1004) setelah tanda %.

---
## Tugas Praktikum

**Soal :**

<div align="center">
<img src="images/soal_tugas.png" width="500"><br>
<em>Gambar 2.3 : Soal Tugas Praktikum</em>
</div>

**Kode Jawaban :**

a. Kode Program "tugas2_2611531004"

In [29]:
# Nama      : Fabian Alhadi Zalinov
# NIM       : 2611531004
# Kelas     : Praktikum Algoritma dan Pemrograman C
# Tugas     : Pekan 2 - Tipe Data, Variabel, dan I/O
# Studi Kasus: Sistem Biodata dan Validasi Kelulusan Praktikan
# Catatan   : Seluruh nama variabel diakhiri 4 digit terakhir NIM (1004)

# ==========================================================
# 1. DEKLARASI KONSTANTA MENGGUNAKAN typing.Final
# ==========================================================
from typing import Final

BATAS_LULUS: Final[float] = 75.0

# ==========================================================
# 2. INPUT DATA PRAKTIKAN
# ==========================================================
print("=== SISTEM REGISTRASI PRAKTIKAN ALPRO 2026 ===")

# Tipe data String, diambil dari input()
nama_1004 = input("Masukkan Nama Mahasiswa : ")

# Tipe data Char (di Python tetap str), memakai petik tunggal/ganda
jenis_kelamin_1004 = input("Masukkan Jenis Kelamin (L/P): ")

# Type casting ke Integer
umur_1004 = int(input("Masukkan Umur : "))

# Type casting ke Float
skor_1004 = float(input("Masukkan Skor Tes Awal : "))

# ==========================================================
# 3. DATA TETAP (ALAMAT MULTILINE & TOKEN KOMPLEKS)
# ==========================================================
# Tipe data String multiline menggunakan tanda petik tiga
alamat_1004 = """
Garegeh,
Kec. Mandiangin Koto Selayan,
Kota Bukittinggi"""

# Tipe data Complex sebagai token identifikasi praktikan
token_1004 = 100 + 3j

# ==========================================================
# 4. PROSES EVALUASI BOOLEAN
# ==========================================================
# Operator perbandingan menghasilkan nilai True atau False
status_lulus_1004 = skor_1004 >= BATAS_LULUS

# ==========================================================
# 5. OUTPUT DATA DISERTAI PENGECEKAN TIPE DATA type()
# ==========================================================
print()
print("=== DATA PRAKTIKAN & HASIL PEMERIKSAAN ===")
print("Nama Mahasiswa :", nama_1004, "| Tipe:", type(nama_1004))
print("Jenis Kelamin  :", jenis_kelamin_1004, "| Tipe:", type(jenis_kelamin_1004))
print("Alamat Domisili:", alamat_1004, "| Tipe:", type(alamat_1004))
print("Umur           :", umur_1004, "tahun | Tipe:", type(umur_1004))
print("Skor Tes Awal  :", skor_1004, "| Tipe:", type(skor_1004))
print("ID Token Sinyal:", token_1004, "| Tipe:", type(token_1004))

print()
print("=== STATUS KELULUSAN PRAKTIKUM ===")
print("Batas Minimum Nilai:", BATAS_LULUS)
print("Apakah Dinyatakan Lulus?:", status_lulus_1004, "| Tipe:", type(status_lulus_1004))

=== SISTEM REGISTRASI PRAKTIKAN ALPRO 2026 ===

=== DATA PRAKTIKAN & HASIL PEMERIKSAAN ===
Nama Mahasiswa : Fabian Alhadi Zalinov | Tipe: <class 'str'>
Jenis Kelamin  : L | Tipe: <class 'str'>
Alamat Domisili: 
Garegeh,
Kec. Mandiangin Koto Selayan,
Kota Bukittinggi | Tipe: <class 'str'>
Umur           : 17 tahun | Tipe: <class 'int'>
Skor Tes Awal  : 88.0 | Tipe: <class 'float'>
ID Token Sinyal: (100+3j) | Tipe: <class 'complex'>

=== STATUS KELULUSAN PRAKTIKUM ===
Batas Minimum Nilai: 75.0
Apakah Dinyatakan Lulus?: True | Tipe: <class 'bool'>


**Output :**

<div align="center">
<img src="images/output_tugas.png" width="400"><br>
<em>Gambar 2.3 : Output Tugas Praktikum</em>
</div>

**Penjelasan :** Program tugas2_2611531004.py dirancang untuk mencatat biodata praktikan sekaligus memverifikasi status kelulusan secara otomatis. Alur programnya sebagai berikut:

1. Deklarasi Konstanta: Nilai batas kelulusan (BATAS_LULUS = 75.0) dideklarasikan di awal program menggunakan typing.Final, sehingga nilainya tidak boleh diubah selama program berjalan.
2. Input Data Praktikan: Program meminta empat data dari pengguna melalui fungsi input():
Nama (nama_1004) dan jenis kelamin (jenis_kelamin_1004) disimpan sebagai tipe str.
Umur (umur_1004) dikonversi ke tipe int menggunakan int(input(...)).
Skor tes awal (skor_1004) dikonversi ke tipe float menggunakan float(input(...)), karena nilainya bisa berupa desimal.
3. Data Tetap: Selain data hasil input, program juga menyimpan:
Alamat domisili (alamat_1004) sebagai string multiline menggunakan tanda petik tiga (""").
Token identifikasi (token_1004 = 100 + 3j) sebagai bilangan bertipe complex.
4. Evaluasi Kelulusan: Status kelulusan (status_lulus_1004) dihitung otomatis dengan membandingkan skor pengguna terhadap BATAS_LULUS menggunakan operator >=, sehingga menghasilkan nilai bool (True atau False).
5. Output Program: Seluruh data yang telah diinput dan diproses ditampilkan ke layar beserta tipe datanya masing-masing menggunakan fungsi type(), sehingga terlihat jelas bahwa program berhasil menerapkan enam variabel dengan lima tipe data berbeda: str, int, float, complex, dan bool.

---
# BAB III
# KESIMPULAN

Berdasarkan praktikum yang telah dilakukan, dapat disimpulkan bahwa setiap data dalam Python memiliki tipe tertentu yang menentukan bagaimana data tersebut dapat diolah, meliputi str, int, float, complex, dan bool. Penamaan variabel yang mengikuti kaidah case-sensitive serta menghindari penggunaan reserved keywords merupakan syarat agar program dapat dijalankan tanpa kesalahan sintaksis.

Penerapan konstanta melalui modul typing.Final terbukti membantu menjaga konsistensi nilai ketetapan seperti batas kelulusan sepanjang program berjalan [3]. Selain itu, praktikum ini menunjukkan bahwa nilai yang diperoleh dari fungsi input() selalu bertipe string, sehingga proses type casting menggunakan int() dan float() mutlak diperlukan sebelum nilai tersebut dievaluasi dengan operator perbandingan. Hasil evaluasi tersebut menghasilkan nilai boolean True atau False yang digunakan sebagai penentu status kelulusan praktikan, dan seluruh tipe data tersebut dapat diverifikasi menggunakan fungsi type().

---
## DAFTAR PUSTAKA

[1] A. Kadir, Dasar Pemrograman Python 3, Yogyakarta: Penerbit ANDI, 2018.

[2] Python Software Foundation, "Built-in Types — Python 3 Documentation," [Online]. Tersedia: https://docs.python.org/3/library/stdtypes.html. [Diakses 20 September 2026].

[3] Python Software Foundation, "typing — Support for type hints," [Online]. Tersedia: https://docs.python.org/3/library/typing.html. [Diakses 20 September 2026].

[4] G. van Rossum, B. Warsaw, dan A. Coghlan, "PEP 8 – Style Guide for Python Code," [Online]. Tersedia: https://peps.python.org/pep-0008/. [Diakses 20 September 2026].